### ISSUE TITLE
Support SAR Speedrun Timer

### ISSUE THREAD

**Issue by JaioCG** [NeKzor/sdp#1]
Currently only `sar_timer_[start/stop]` is supported, which is deprecated and not used by categories/mtriggers. Instead, `sar_speedrun` timer should be used for speedrun timing instead.

Currently in sdp, the SAR timer module checks for the commands `sar_timer_[start/stop]`, simply changing these to be the speedrun timer won't work since those aren't manually ran, but instead are automatically checked, and the SpeedrunTimer::Start() function runs in SAR. Not really sure the best way about fixing this.

**Comment by NeKzor** [comment]
This will take a while because I noticed a lot of issues when porting the library to TypeScript which I want to fix in 1.0. It will most likely be introduced as ~~`SarSpeedrunTimer`~~ in a separate module. Reusing the code that is used from the [autorender project](https://github.com/NeKzor/autorender/blob/1538ff84a0b2137100c74025622a28607619c178/src/server/sar.ts#L214-L251) is probably a good start.

**Comment by NeKzor** [comment]
Fixed in version 0.10:
* Added [utils](https://jsr.io/@nekz/sdp/doc/utils) to extract SAR data and Steam IDs
* Added `readVarInt32` to buffer class to write custom engine parser like strata, cs:go etc. ([example](https://github.com/NeKzor/sdp/blob/d30752e99debd893d044fab7870650682e97fb18/examples/custom/strata.ts#L140-L144))
* Introduced `/speedrun`, `/types`, and `/utils` exports
* [Breaking Change] Speedrun related timers can only be imported from `/speedrun`
* Available in [jsr.io/@nekz/sdp](https://jsr.io/@nekz/sdp) (npm is still supported)

Here is an example:
https://github.com/NeKzor/sdp/blob/438a8af5258234186934547405192034a5300b75/examples/info/sar_data.ts#L11-L16

I originally planned to put everything into 1.0 but that still requires a lot of bug fixing and refactoring.
