### ISSUE TITLE
Support for STV demos (server side demo) for TF2

### ISSUE THREAD

**Issue by Hona** [NeKzor/sdp#2]
Awesome tool. Works on POV demos for tf2.

Working on integrating this with Rocket Jump/Sticky Jump STV demos. Chat logs has helped heaps but if we can get more data that would be awesome

It would be nice to fetch out position, velocity or even projectiles (rockets/stickies/pipes).

**Comment by NeKzor** [comment]
I don't think you want to use sdp with TF2 since the library is mainly focused on single player games and it's not advanced enough for your use case. Have you seen [demostf/demo.js](https://github.com/demostf/demo.js)? Looks like you already found their latest parser. Getting specific properties of entities is something you should be able to to with PVS and SendProp parsing. This is something that sdp cannot do.

**Comment by Hona** [comment]
Thank you for the quick response. As you noticed, I did find the [demostf/parser](https://github.com/demostf/parser). It does almost everything and I'll work on extending it myself/asking for them to extend the functionality.

BTW, your work documenting demo file format, the web viewer, auto recorder etc all look like great work! :)
